# Generated by Django 3.0.1 on 2020-01-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bot_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=1000)),
                ('keyword1', models.CharField(blank=True, max_length=100)),
                ('keyword2', models.CharField(blank=True, max_length=100)),
                ('keyword3', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('sender', models.CharField(blank=True, max_length=5)),
                ('chat_owner', models.CharField(blank=True, max_length=100)),
                ('time', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
